### ISSUE TITLE
make chunked fails

### ISSUE THREAD

**Issue by serbanghita** [kallerosenbaum/grokkingbitcoin#19]
```
gali@gali-VirtualBox:~/grokkingbitcoin$ make chunked
asciidoctor -b html5  -a fm -b html5 grokking-bitcoin.adoc -o build/grokking-bitcoin-fm.html
rm -rf build/style
ln -sfr style build
asciidoctor -b html5  -r ./hacks/sectnumoffset-treeprocessor.rb -a sectnumoffset=$((1-1)) -a ch1 grokking-bitcoin.adoc -o build/grokking-bitcoin-1.html
asciidoctor -b html5  -r ./hacks/sectnumoffset-treeprocessor.rb -a sectnumoffset=$((2-1)) -a ch2 grokking-bitcoin.adoc -o build/grokking-bitcoin-2.html
asciidoctor: FAILED: /home/gali/grokkingbitcoin/grokking-bitcoin.adoc: Failed to load AsciiDoc document - undefined method `number=' for #<Asciidoctor::Section:0x00005585cda0e148>
Did you mean?  number
               numbered=
               numbered
  Use --trace for backtrace
make: *** [Makefile:42: ch2] Error 1
```

ps: I also had to increase the memory because it was failing with 137 (memory or space issues)

**Comment by serbanghita** [comment]
I removed the ruby script `-r ./hacks/sectnumoffset-treeprocessor.rb` and it worked

**Comment by kallerosenbaum** [comment]
Sorry for late response. Which version of asciidoctor did you run? It's only tested to work on asciidoctor >= 1.5.7 and < 2.0.

I have as a long standing goal to make it work with asciidoctor 2.x.

**Comment by serbanghita** [comment]
@kallerosenbaum thanks for the reply, I was using
```
Asciidoctor 2.0.12 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

I'll close this, since it works as expected, you already specified in the README that you support `Asciidoctor >= 1.5.7 and < 2.0`. I wasn't paying attention 🤦  🙇

**Comment by kallerosenbaum** [comment]
@serbanghita I've pushed changes to master branch. I have now tested with asciidoctor 2.0.12 and it works for me. Please reopen this if it doesn't work for you on version >=2.0.12.
